---
# unforuntely required to ensure that whatever unarchive uses for getting archive from github
# works with openssl on default docker images :( sorry.
- name: Ensure curl is installed
  package:
    name: curl
    state: installed

- name: Find out latest download url of rkt from github
  github_release:
    token: "{{ github_login_token }}"
    user: "coreos"
    repo: "rkt"
    action: get_asset_url
    asset_regex: ".tar.gz$"
    release_version: latest
  register: rkt_release
  delegate_to: 127.0.0.1

- name: Download and extract archive from github releases for rkt
  unarchive:
    src: '{{ rkt_release.asset_url }}'
    remote_src: yes
    dest: /opt/
    creates: /opt/rkt-{{ rkt_release.tag }}

- name: Copy binarys to path
  copy:
    remote_src: true
    src: /opt/{{ item.base }}-{{ item.version }}/{{ item.base }}
    dest: /usr/bin/
    mode: 0755
  with_items:
    - base: "rkt"
      version: "{{ rkt_release.tag }}"